### ISSUE TITLE
Todo notes...

### ISSUE THREAD

**Issue by mrKornelius** [Davod0/App-Development-Household-Application#112]
Kommer använda denna issun för lite TODO anteckningar på saker som behöver fixas

**Comment by mrKornelius** [comment]
- [ ] Använd .trim() på inmatad text. För att undvika namn med mellanslag i slutet 

![Image](https://github.com/user-attachments/assets/357fd48f-b5ba-45bb-bb3f-534325c27342)

**Comment by mrKornelius** [comment]
- [ ] HouseholdInformation ska inte ta emot någon parameter, finns på vissa ställen (sätt undefined i RootStackNavigator för att se var det blir fel.

**Comment by mrKornelius** [comment]
- [ ] SelectedHousehold filter on task.isArchived

**Comment by mrKornelius** [comment]
- [ ] En funktion som kan filtrera ut lediga avatars från ett hushålls-id
- [ ] Radera en Task på riktigt (inklusive completedTasks)
- [ ]

**Comment by mrKornelius** [comment]
- [ ] TaskInfoScreen tar emot en parameter snyggt, På EditTaskScreen ser det helt annorlunda ut och jättekrångligt, ändra så det är som på TaskInfoScreen.

**Comment by mrKornelius** [comment]
- [ ] scrollView på Yourhouseholds!!!!!

**Comment by mrKornelius** [comment]
1. Login och Signup visa felmeddelanden
2. logga in och kör en reload i consolen (fortfarande inloggad) Splashscreen visas
4. Visa YourHousholds - 
  - InfoHousehold 
  - Skapa hushåll
  - Gå med i hushåll - (visa med fel kod)
5. Välj hushåll
  - byt hushåll
  - skapa syssla
  - utföra task - be Magnus utför en task
  - visa statistik
  - utföra en task till - statistik uppdateras
  - redigera en syssla
  - ta bort syssla
  - byta namn på hushåll
  - visa profil, darkmode, visa statistik i darkmode
  -  (edit profile, byt och avatar)
6. Gå tillbaka till YourHouseholds
  - visa ett hushåll med 2 st requests
  - rejecta en och accepta en
  - visa hushålls info (ny medlem finns)
  -

**Comment by mrKornelius** [comment]
- [ ] fix request on own household
- [ ]

**Comment by mrKornelius** [comment]
- [ ] delete all console.log() spamming
